Add technohaven
MBSTUPC/tech-companies-in-bangladesh pull request #97
Opened 2023-12-28 05:58 UTC by mmmim24

2023-12-28 07:31 UTC, mmmim24 commented
further added Ixora and sjinnovation

2023-12-28 07:46 UTC, mmmim24 commented
RiseUp Labs added

2024-01-20 19:02 UTC, mmahmoodictbd commented
Please check comments

2024-03-11 02:31 UTC, mmmim24 commented
Can anyone please review these changes please?

2024-03-11 09:09 UTC, mmahmoodictbd commented
> Can anyone please review these changes?

Can you please check my comments? TLDR; Put addresses in a single line, see the images I added.


![Screenshot 2024-03-11 at 10 08 18](https://github.com/MBSTUPC/tech-companies-in-bangladesh/assets/1731977/16cc1dc6-c99d-4863-8e54-dfa065fec008)

![Screenshot 2024-03-11 at 10 08 41](https://github.com/MBSTUPC/tech-companies-in-bangladesh/assets/1731977/0848959f-4468-4ef8-92b5-2345c4261a66)

2024-03-13 16:49 UTC, mmmim24 commented
done

2024-03-13 18:02 UTC, arafat-hasan requested changes

2024-03-13 18:02 UTC, arafat-hasan commented on README.adoc
> +|NodeJS,Angular,Rust,React,Android,iOS,Machine Learning,Blockchain
add spaces after commas

2024-03-13 18:02 UTC, arafat-hasan commented on README.adoc
> +|React,Objective C,Java,Kotlin,Flutter,Swift,Blockchain
add spaces after commas

2024-03-13 18:02 UTC, arafat-hasan commented on README.adoc
> +|Flutter,Swift,Kotlin,Typescript,React,Java,DJango,NodeJS,SQL etc.
add spaces after commas

2024-03-13 18:02 UTC, arafat-hasan commented on README.adoc
> +|React,Vue,TypeSCript,NodeJS,Django,SpringBoot,Flutter,Swift,SQL,MongoDB etc.
add spaces after commas

2024-03-14 07:37 UTC, arafat-hasan requested changes
@mmmim24,  Would you please resolve the merge conflict?

2024-03-14 09:51 UTC, mmahmoodictbd approved these changes

2024-03-14 09:52 UTC, mmahmoodictbd commented
I approved the PR, please fix the conflict then we can merge it.

2024-03-14 10:42 UTC, closed without merging